 export default 
    {
        "RECORDS": [
          {
            "RecID": "1",
            "WOWDate": "2020-05-03",
            "WOWTopic": "EXCELLENCE IS YOUR TRADEMARK",
            "WOWBiblePassage": "Esther 2: 8-17",
            "WOWMemoryVerse": "1 Peter 2:9",
            "WOWMessage": "A very popular Yoruba adage, when translated, says, “You can’t see a prince without taking cognizance of his royal emblem.” Welcome to your month of Excellence beloved, where great lines shall fall unto you in pleasant places. By reason of Jesus’ death on the Cross, excellence was one of those inheritances which was conferred on you as God’s child. Your DNA was divinely mutated from a common person to a royal priesthood. Since the very day you accepted Jesus into your life, you were baptized into His death as well as into His royalty. God placed His Spirit – which is the Spirit of excellence into you as a seal of ownership [2 Cor. 1:21-22]. Just as every company/restaurant has their peculiarity and logo; so does every child of God. Your logo is absolute excellence; for, “God’s Spirit never enters a man and then lets him live like the world. You can be sure of that.” (A.W. Tozer)\r\nIf you look closely at God’s creation, you would be able to trace His signature of perfect excellence. In the sense that, the elemental forces (i.e. the sun, moon, and stars) barely interfere with themselves. And you can also see how the clouds are being hung in the sky for many millennia. If God can be known for excellence, how much more we His children? This invariably implies that, if we have not begun to exhibit excellence in every sphere of our lives, then we are only bringing nothing but shame to His name. Beloved, you were redeemed to excel, and not to struggle. If Joseph could exhibit excellence in prison, then why are you blaming those unfavorable circumstances? If Esther could also exhibit excellence in a royal beauty contest, regardless of her poor background, then what is holding you back from walking in this reality? Jesus already paid the price for you; all you need do is: Believe Him and in what He has done for you, and appropriate this inheritance via your corresponding diligent actions. In your academics, you are not permitted to soil that trademark of excellence. At your workplace, you are only expected to excel beyond status quo; nothing less! At all times, you must learn to declare excellence into your endeavors as you work in its consciousness. You have been redeemed to stand before kings, and not mean men! You have a godly heritage, so ensure you appropriate it judiciously.",
            "WOWPrayerPoint": "Father, enable me to walk in the reality of your signature at all times"
          },
          {
            "RecID": "2",
            "WOWDate": "2020-05-04",
            "WOWTopic": "THE BLESSEDNESS OF CONSECRATION",
            "WOWBiblePassage": "1 Sam. 2: 12-20",
            "WOWMemoryVerse": "Psalm 1:1",
            "WOWMessage": "Every promise/blessing of God always requires attitudinal co-ordination for expression. We cannot confer on ourselves the license to live unsanctified lives because excellence is our supposed signature. In as much as we are a peculiar people, we are also a HOLY NATION. There is a very high degree of personal consecration that is divinely expected of us in order to stay afloat, in the midst of the storm. Unfortunately, we live in a dispensation where holiness has been overemphasized and tossed into the trash can. The Christians of today would readily compromise sanctity for fame, recognition, positions, wealth, and material success. We have begun to lose sight of the immeasurable blessings that accompany a consecrated life. We have forgotten that, “Holiness exalts a nation, but sin is a reproach to any people.” [Prov. 14:34]. Oh, don’t you know that the longevity of one’s excellence is solely hinged on personal consecration? Of a truth, unbelievers may seem to succeed in their endeavors; but wait for a man/woman of refined character, and observe to see whose work would be more outstanding.\r\nDuring Bible times, the whole world celebrated Samuel as the greatest prophet in his generation; but how silent was his consecration amongst the perverse sons of Eli. Beloved, do you know that Samuel had every excuse, every reason to act like Hophni and Phinehas, but he didn’t! He was raised under the administration of Eli, but separated himself from the evil deeds of Eli’s house. As a result, he became a prophet whose words never fell to the ground. That’s Prophecy par excellence! Don’t you think it’s high time you stopped giving excuses for your compromised state? The fact that your boss’/pastor’s son is perpetrating that mischievous act doesn’t license you to do same. There is a seal of excellence that had been placed on you by your Righteous Father. Hence, you cannot afford to live base on circumstantial inadequacies. You must be deliberate about that consecration demand: By stop having illicit affairs with that lady/that man; by stop selling your body cheaply to that lecturer just for a unit credit in that course; by separating yourself from that compromised crowd at work. No one leaves his/her consecration demand to chance and in the long run lives an extraordinary life. For God cannot be mocked! Remember, “People see the success, but God honors the SACRIFICE.” (Bishop T.D Jakes)\r\n",
            "WOWPrayerPoint": "Oh Lord, please thresh every weakness in my life as you consecrate me under your wings"
          },
          {
            "RecID": "3",
            "WOWDate": "2020-05-05",
            "WOWTopic": "ETERNITY’S MAGNIFYING GLASS",
            "WOWBiblePassage": "1 Sam. 13: 5-14",
            "WOWMemoryVerse": "Acts 13: 36",
            "WOWMessage": "We live in a competitive environment where everybody tries to do almost everything in order to stay afloat life’s game. But we have forgotten that in trying to do everything, we invariably lose relevance. Most of us take some actions based on unhealthy comparisons. “My friend is driving a Lexus Jeep now, and I’m yet to even buy a car. My colleague has gained admission before me, and I’m still writing JAMB.” All these comparisons could fill today’s devotional, but to what end? Sometimes, we miss what God has in stock for us because we try to live our lives according to other people’s progress. You must learn to focus your life in God’s purpose. Stop trying to do what everyone is doing; instead begin to focus on what God wants you to do, how He wants you to do it, and who He wants you to be. It’s high time you began to channel that desperation and passion towards eternity’s magnifying glass – Purpose. Focusing your life via God’s purpose in turn makes you a laser beam in your endeavors. This way, you channel your commitments, energies, and time into things that have eternal relevance.\r\nPastor Rick Warren (in his renowned book: Purpose-Driven Life) penned, “Being successful and fulfilling your purpose are not at all the same issue! You could reach all your personal goals, becoming a raving success by the world’s standard, and still miss the purposes for which God created you.” When you become oblivious of God’s purpose, you place premium values on important irrelevances, and then you exhaust your energy trying to fit into different molds of success. You unconsciously begin to act like King Saul, who lost sight of His purpose on earth, and began to do priestly duties all in the name of trying to do everything. Has God purposed you to study in that university? Has he affirmed you submitting your application letter to that firm? Or don’t you know that God has prepared the right place, the right people, and the rightful position for you? This is the more reason you must always seek His will concerning any subject matter in order to access the right strategies towards appropriating those packages. Beloved, a true believer doesn’t live by luck/chance; they live according to purpose, according to the leading of the Holy Spirit. So stop running the Rat Race of life, and start focusing your life via purpose today!\r\n",
            "WOWPrayerPoint": "In the midst of life’s pressures, LORD empower me to always fulfill purpose.  "
          },
          {
            "RecID": "4",
            "WOWDate": "2020-05-06",
            "WOWTopic": "HOW FAR CAN YOU SEE?",
            "WOWBiblePassage": "Genesis 13: 14-17",
            "WOWMemoryVerse": "Habakkuk 2:2",
            "WOWMessage": "The way you see your life shapes how you live it. Today’s devotional is a corollary to yesterdays. After having focused your life via eternity’s magnifying glass (purpose), how can you surmount the Rat Race of life? I believe staying committed to your vison adequately answers this question. Do you know that the farther you look away from your vision, the less likely you are to achieving God’s purpose for your life? A larger percentage of unsuccessful people on earth looked away from their vision just at the brink of their breakthroughs. While the remaining percentage of status-quo successes allowed themselves to get talked out of their vision. The truth is: There is one person who can give the accurate view of what your future holds. That person is the Only-Wise God! He holds your future in His hands, and He is willing to reveal certain details about your future to you. \r\nGod’s intention for His children is that we stay focused to His course and purpose, and one of those ways is to keep our vision in front of us. Take Father Abraham for instance. When God called him; not only did He give Abraham a promise, but also did He show him a picture to look at. God showed him the stars in the sky, and the sands on the seashore in order to keep Abraham in sync with His purpose. Abraham could have compromised that promise or would have even gotten talked out of it if he didn’t keep that vision in front of him. The Message Version of today’s Golden Verse says, “And then God answered: ‘Write this. Write what you see. Write it out on BIG BLOCK LETTERS, so that it can be read on the run.’” Little wonder Abraham consequently inherited the promise, for he wrote that vison in his heart in BLOCK LETTERS. Joel Osteen penned, “We constantly move towards what we see.” The Holy Spirit is asking you dear reader that: How far can you see yourself in that business in the next 5 years? Hope you are not allowing circumstantial inadequacies to cloud your vision?  The closer you keep your vision in front of you without getting talked out of it, the more diligently God becomes committed towards its fruition.  Today, by reason of you reading this devotional and applying it; the LORD shall put an end to every struggle in your academics and career in Jesus name. Peace.\r\n",
            "WOWPrayerPoint": "Oh LORD, help me to stay committed to the vision of my life in Jesus name."
          },
          {
            "RecID": "5",
            "WOWDate": "2020-05-07",
            "WOWTopic": "EMBRACE YOUR UNIQUENESS",
            "WOWBiblePassage": "Exodus 31: 1-6",
            "WOWMemoryVerse": "2 Cor. 4:7",
            "WOWMessage": "No two persons on this earth have equal and parallel individuality; for even identical twins act very differently. If this truth is firmly established, why then do people lose their uniqueness trying to live like someone else?  An interview was made in a hospital in the US several years ago, and a major reoccurring statement of regret was observed from dying patients, “I wish I had been true to who I was and not just lived to meet the expectations of others.” When you live your life out of insecurity (worrying about what others think about you); there would be an exhaustion of energy, because you would want to gain your siblings’/boss’/friends’ approval, and in turn gradually lose your uniqueness. Everyone has a right to his/her opinion, so trying to respond to everybody’s criticism only makes you less of whom God created you to be. You may be your best self yet, but have you even taken time to appreciating God’s dexterity of uniqueness in your life? You could take out 2 minutes to do that now, beloved.\r\nJust as it is onus on every believer to always celebrate our unique skill or character, it is also expedient to remind ourselves that our existence on earth was a deliberate act of God. God deposited a distinguishing feature in every creature in order for His glory to be made manifest. When God created the animals, He blessed every animal with a peculiarity, and each of them embraces their individuality. This implies that it is absolutely wrong to judge a fish by its ability to climb a tree. Consequently, it is so unwise to compare yourself with every other person. You were carefully conceived in the mind of God; hence, there was no accident in your genetic configuration. Don’t you know that there is an anointing on your life, and there’s an empowerment to be you and not someone else? Why don’t you allow that anointing to find full expression in your life just like it did the lives of Bezalel and Oholiab? These men had a uniqueness of creativity, and they embraced it dearly. In your workplace, of what relevance is your skill? Have you been able to dispense essence via your uniqueness at school? God hasn’t placed you there just for you to act like your colleague or predecessor. He has placed you there for you to be the authentic you.\r\n",
            "WOWPrayerPoint": "Father, please open the eyes of my heart that I may discover that unique, but hidden virtue in me. "
          },
          {
            "RecID": "6",
            "WOWDate": "2020-05-08",
            "WOWTopic": "NO YARDSTICK, NO LANDMARK!",
            "WOWBiblePassage": "Daniel 1: 1-8; 18-20",
            "WOWMemoryVerse": "Daniel 1:8",
            "WOWMessage": "For every outstanding success, there is always a unique caution to be adhered to. Despite the fact that the skies and the seas both have a similarity, there is a divine distinction that is still at work in these entities. If God could place a yardstick between his creation, how much more us believers? Often times, we tend to find ourselves joining the band wagon; maybe as a result of fear of segregation/criticism or loneliness. This compromise has cost us some eternal blessings. We will not fully actualize exploits in our endeavors if we continue to cling to some associations, habits or rightful excuses. Most people, having enjoyed the temporary benefits of their colleagues, forget to DRAW THE THIN LINE where need be. No one acts ordinarily/arbitrarily and then produces extraordinary results. There must definitely be a restraint, a yardstick, a distinction between you (a child of excellence) and every other person in your workplace or school. Are you ready to consent to that restraint today, beloved?\r\nThe degree of a man’s success is equivalent to the level of his sacrifice. You must learn to shed some habits, some acquaintances, some frivolities, if you are going to trail-blaze in your career/academics. Your resistance to living a sacrificial life only depicts your uncertainty of God’s purpose. Daniel and his friends had all the leverage to eat the king’s delicacies; but they declined because they knew that they were on a mission in Babylon. They willingly denied themselves of the rightful Babylonian luxuries for the greater cause of fulfilling God’s purpose in a foreign land. All things are lawful, but not all things are expedient. [1 Cor. 6:12] It is good to make friends at work or in school, but it isn’t substantial to spend the bulk of your time with ALL your friends. You’ve got to realize that some people as well as activities have gained mastery in becoming time wasters, so failure to applying the yardstick principle would cloud your discretion to pruning these excesses. Even our Lord Jesus understood the principle of having to restrain himself to being alone with the Father. The truth is: If Jesus had left His personal seclusion to chance, He would have jeopardized purpose. This means that no one will actually give you the opportunity of making that sacrifice. So, until living sacrificially becomes your lifestyle, becoming ten-times-better than your peers would only remain a wish.\r\n",
            "WOWPrayerPoint": "Teach me Oh LORD to restrain myself from life’s frivolities and excesses in Jesus name."
          },
          {
            "RecID": "7",
            "WOWDate": "2020-05-09",
            "WOWTopic": "EXCEPTIONAL QUALITIES",
            "WOWBiblePassage": "Gen 24:10-22 / Gen 24:42-48",
            "WOWMemoryVerse": "Gen 24:46",
            "WOWMessage": "Being normal will not always be appreciated because we have a lot of other people standing in that line; exceptionality stands you out no matter what. Being exceptional sometimes looks very boring and unnoticed. For instance, picking up dirt along the hallway at work, or having to leave work 20minutes after closing hours or having to stay behind in class in order to assimilate the day’s lecture. In today’s passage, did you realize that it would have taken quite a large amount of water to quench the thirst of ten travel-weary camels? And considering the size of a pitcher, multiple trips would have to be made to the well to get that amount of water. Well, there was a lady who didn't consider that stress and the fact that she wasn't going to get paid for it. She only saw a space that needed filling; a need that required meeting, and she did it exceptionally. I'm sure the camels didn't ask Rebekah for water (asking would have been pretty weird though) and even Eliezer forgot to ask on their behalf. He had only asked for water for himself, but I'm sure Rebekah thought of the distance the camels had come without water and felt the urge to quench their thirst. If Rebekah had only given Eliezer water he asked for leaving out the camels, she wouldn't have met the criteria/quality that he had prayed for, thereby, robbing herself of the intended marriage. \r\nExceptionality will always require that you think out of the box to see beyond the present need. How many times have we robbed ourselves of good things that are rightfully ours because we aren't willing to go the extra mile? Peculiarity is in your DNA as a child of God; He didn't create you to just go with the flow, hence, your exceptional current should direct the flow of others. Your Father hasn't placed you here to settle for mediocrity, He intends for you to be exceptional and He has given you every spiritual blessing in heavenly places required to do so. Go the extra mile, think out of the box, add more hours to your study time, attend that training, take that next step, register for that extra course, burn the midnight candle... The camels won't ask for water, you're supposed to figure it out and quench their thirst, because in that simple act lies your transformation from a maiden to a bride, and not just a bride, but a partaker in an everlasting covenant and mother to nations. You never really know who's watching out for you, rise above the average standard and break the bars, there's glory at the end.\r\n",
            "WOWPrayerPoint": "Oh Lord, help me to live as a peculiar person that you have called me out to be in Jesus name."
          },
          {
            "RecID": "8",
            "WOWDate": "2020-05-10",
            "WOWTopic": "WHEN EVERYONE BOWS",
            "WOWBiblePassage": "Daniel 3:13-18",
            "WOWMemoryVerse": "Matthew 10:28",
            "WOWMessage": "A fiery furnace might sound scary, but it shouldn't make you lose your faith because you are the progeny of The Consuming Fire. Your Father owns the key to all doors; He is the ruler of the whole universe, mere men should not dare to scare you into bowing to their own way of life. The fact that everyone does something doesn't mean it is right for you to do it too, and I'm sure you know a million things that fall into this space. And if anyone is bold enough to ask you why you are not 'bowing', your reply should be: 'I have no need to answer you in this matter'. Frankly speaking, you have no business explaining your allegiance to anyone, let the Fourth One in the fire justify you. The three Hebrew boys had not bowed, will not bow, and were still not willing to bow down to whatever image king Nebuchadnezzar had put up. The reality of losing their positions as rulers of the province didn't scare them into it and neither did the flames of the fiery furnace. It is not okay to indulge in malpractice just because it has become the 'norm' and you'll be regarded as an outcast if you don't; as a child of God, you define the norms! It is not right to falsify your age for a job that won't even last for half of your stay here on earth. It is not okay to go along with that lie in the office because you're scared of higher authorities. \r\nDon't compromise God’s standard all in the name of trying to please people or going along with the flow of things. A slight inclination to error perverts the whole journey and makes waste of all previous efforts. Never allow societal pressure mess with your head to the point where you give in to conformism. You have not been called out of darkness only for you to still act according to their policies and guidelines. Your Father has standards that you're expected to live by; you're in the world but not of the world. \"Our God, whom we serve is able to deliver us from the burning fiery furnace and He will deliver us from your hands\". These boys had total trust in the limitless power of their God to save them. They trusted Him enough to perish for His glory, they were definitely sticking with Him no matter the outcome. But God showed up and stopped the show just for them, because He never allows His own to be put to shame. They that trust in the Lord and refuse to bow at the call of the world, shall be as mount Zion, which cannot be moved but abides forever.\r\n",
            "WOWPrayerPoint": "Even when societal pressure gets to its height, help me to keep my eyes single and refuse to bow in Jesus name."
          },
          {
            "RecID": "9",
            "WOWDate": "2020-05-11",
            "WOWTopic": "WATCHMAN UNTO RIGHTEOUSNESS",
            "WOWBiblePassage": "Ezekiel 33:1-9",
            "WOWMemoryVerse": "Ezekiel 33:7",
            "WOWMessage": "In ancient times; watchmen were given great honor, because they served as the eye of the city. Even the greatest and largest army depended on the very sensitive role of a watchman or watchmen, as the case may be. They are set to watch; they keep guard especially by night from a higher position. Giving warning signals is their major role, they create awareness of any impending danger that might be around the corner. This is definitely an important role for sensitive person; because without the warnings of a watchman, enemy troops could easily sneak in and defeat even the most prepared army. Watchmen are never slack in their role because they are properly aware of the kind of tragedy their slothfulness could cause. They understand their position as the eyes of the troop and fight to remain awake when others are far gone into the land of sleep. They are always on the lookout, checking and rechecking to see if they've not let down their guard. They know the appropriate time to send out warnings and the right signals to use at every point in time. They are responsible for the overall safety of everyone in the camp or wherever they watch over.\r\nGod has set you as watchman unto the whole world; therefore, you hear the word from His mouth and give the people warnings from Him. You are a watchman in your department: God has put you in charge of so many people, to warn them of things to come, to avert the plans of the enemy, and to uphold the banner of righteousness. As long as you're in the world, you are the light of the world; a watchman charged with the responsibility of guiding others until they come to a knowledge of the light. For you to truly be the watchman that God has called you out to be, the above-mentioned responsibilities and more are what you must carry out. Your failure to warn the wicked from their ways puts you in a position where you have to answer for their blood. Your role is a big one and you can't afford to play around, there is no room for slothfulness because lives depend on you. God has placed you in that position at work so as to saturate and promote righteousness there. As you go out today, occupy your rightful position as a watchman unto righteousness as you right all the wrongs around you using the word of God. \r\n",
            "WOWPrayerPoint": "Lord, strengthen me to always uphold the banner of righteousness for you in Jesus name. Amen!"
          },
          {
            "RecID": "10",
            "WOWDate": "2020-05-12",
            "WOWTopic": "WHERE IS THY STAFF?",
            "WOWBiblePassage": "1 Sam. 17: 20-24; 26-40",
            "WOWMemoryVerse": "Psalm 23:4",
            "WOWMessage": "Having a staff, in ancient times was quite peculiar to nomads/shepherds. Most people believed that staffs were used to indicate authority or leadership. But do you know that there is an untold truth about staffs? In the Old Testament, you would discover that all shepherds had a staff – Moses, David etc. Unlike in this Jet Age where historical events are recorded and stored via electronic means; then the shepherds usually etch historical events/personal encounters on their staffs. They often did this to REMIND themselves of God’s mightiness over their lives. Beloved, could you imagine Brother Moses (having had the encounter of the burning bush) etching that experience on his staff; alongside all the experiences of the ten plagues in Egypt, and having to approach the Red Sea. Little wonder our LORD instructed him to stretch forth that selfsame staff towards the sea; for by Moses seeing those memories on his staff, his faith was stirred up in God, and a miracle was birthed. Halleluyah!\r\nJust as Joel Osteen penned, “What you remember will always have a great impact on what kind of life you live.” How often do you remember the wondrous works of God in your life? Or have you continually allowed yourself to be intimidated by the size of that giant/obstacle in your career, academics, and ministry? If we look intently at David’s life: He was just a teenage shepherd boy. He had come across a lion and a bear on several occasions, and God had given him victory over them. So, when it was time to face Goliath, he took his staff alongside his slingshot. David had definitely etched his victories (over the lion and bear) on that staff. He would have also etched on that staff the day he was anointed king by Samuel. So, as he approached that giant, he would have glanced at his staff countless times to get a boost in his faith in God. And alas, victory was his! Dear reader, are you been faced with a mountain, a giant, or even a Jericho in your academics/business at the moment? Have you limited the power of the Omnipotent One through fear and unbelief? Today, you need to get your staff out towards that situation, and secure your victory over it. Your source of comfort, just as David recounted in today’s verse, is in the Shepherd’s staff. The reason is that your staff is a POINTER that God will redo that miracle again.\r\n",
            "WOWPrayerPoint": "As I stretch out my staff towards these situations (mention them), I secure victory over them in Jesus name."
          },
          {
            "RecID": "11",
            "WOWDate": "2020-05-13",
            "WOWTopic": "WHERE IS THY STAFF2 ?",
            "WOWBiblePassage": "1 Sam. 17: 20-24; 26-40",
            "WOWMemoryVerse": "Psalm 23:4",
            "WOWMessage": "Having a staff, in ancient times was quite peculiar to nomads/shepherds. Most people believed that staffs were used to indicate authority or leadership. But do you know that there is an untold truth about staffs? In the Old Testament, you would discover that all shepherds had a staff – Moses, David etc. Unlike in this Jet Age where historical events are recorded and stored via electronic means; then the shepherds usually etch historical events/personal encounters on their staffs. They often did this to REMIND themselves of God’s mightiness over their lives. Beloved, could you imagine Brother Moses (having had the encounter of the burning bush) etching that experience on his staff; alongside all the experiences of the ten plagues in Egypt, and having to approach the Red Sea. Little wonder our LORD instructed him to stretch forth that selfsame staff towards the sea; for by Moses seeing those memories on his staff, his faith was stirred up in God, and a miracle was birthed. Halleluyah!\r\nJust as Joel Osteen penned, “What you remember will always have a great impact on what kind of life you live.” How often do you remember the wondrous works of God in your life? Or have you continually allowed yourself to be intimidated by the size of that giant/obstacle in your career, academics, and ministry? If we look intently at David’s life: He was just a teenage shepherd boy. He had come across a lion and a bear on several occasions, and God had given him victory over them. So, when it was time to face Goliath, he took his staff alongside his slingshot. David had definitely etched his victories (over the lion and bear) on that staff. He would have also etched on that staff the day he was anointed king by Samuel. So, as he approached that giant, he would have glanced at his staff countless times to get a boost in his faith in God. And alas, victory was his! Dear reader, are you been faced with a mountain, a giant, or even a Jericho in your academics/business at the moment? Have you limited the power of the Omnipotent One through fear and unbelief? Today, you need to get your staff out towards that situation, and secure your victory over it. Your source of comfort, just as David recounted in today’s verse, is in the Shepherd’s staff. The reason is that your staff is a POINTER that God will redo that miracle again.\r\n",
            "WOWPrayerPoint": "As I stretch out my staff towards these situations (mention them), I secure victory over them in Jesus name."
          }
        ]
      }


// export default AllWord;